
import { VideoData } from './types';

export const COUNTRIES = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AX', name: 'Åland Islands' },
  { code: 'AL', name: 'Albania' },
  { code: 'DZ', name: 'Algeria' },
  { code: 'AS', name: 'American Samoa' },
  { code: 'AD', name: 'Andorra' },
  { code: 'AO', name: 'Angola' },
  { code: 'AI', name: 'Anguilla' },
  { code: 'AQ', name: 'Antarctica' },
  { code: 'AG', name: 'Antigua and Barbuda' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AW', name: 'Aruba' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'AZ', name: 'Azerbaijan' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BY', name: 'Belarus' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BZ', name: 'Belize' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BM', name: 'Bermuda' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BA', name: 'Bosnia and Herzegovina' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BV', name: 'Bouvet Island' },
  { code: 'BR', name: 'Brazil' },
  { code: 'IO', name: 'British Indian Ocean Territory' },
  { code: 'BN', name: 'Brunei Darussalam' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'KH', name: 'Cambodia' },
  { code: 'CM', name: 'Cameroon' },
  { code: 'CA', name: 'Canada' },
  { code: 'CV', name: 'Cape Verde' },
  { code: 'KY', name: 'Cayman Islands' },
  { code: 'CF', name: 'Central African Republic' },
  { code: 'TD', name: 'Chad' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CX', name: 'Christmas Island' },
  { code: 'CC', name: 'Cocos (Keeling) Islands' },
  { code: 'CO', name: 'Colombia' },
  { code: 'KM', name: 'Comoros' },
  { code: 'CG', name: 'Congo' },
  { code: 'CD', name: 'Congo, Democratic Republic' },
  { code: 'CK', name: 'Cook Islands' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'CI', name: 'Cote D\'Ivoire' },
  { code: 'HR', name: 'Croatia' },
  { code: 'CU', name: 'Cuba' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'DK', name: 'Denmark' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'DM', name: 'Dominica' },
  { code: 'DO', name: 'Dominican Republic' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EG', name: 'Egypt' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea' },
  { code: 'ER', name: 'Eritrea' },
  { code: 'EE', name: 'Estonia' },
  { code: 'ET', name: 'Ethiopia' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)' },
  { code: 'FO', name: 'Faroe Islands' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'GF', name: 'French Guiana' },
  { code: 'PF', name: 'French Polynesia' },
  { code: 'TF', name: 'French Southern Territories' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GE', name: 'Georgia' },
  { code: 'DE', name: 'Germany' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GI', name: 'Gibraltar' },
  { code: 'GR', name: 'Greece' },
  { code: 'GL', name: 'Greenland' },
  { code: 'GD', name: 'Grenada' },
  { code: 'GP', name: 'Guadeloupe' },
  { code: 'GU', name: 'Guam' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GG', name: 'Guernsey' },
  { code: 'GN', name: 'Guinea' },
  { code: 'GW', name: 'Guinea-Bissau' },
  { code: 'GY', name: 'Guyana' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HM', name: 'Heard Island and Mcdonald Islands' },
  { code: 'VA', name: 'Holy See (Vatican City State)' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IS', name: 'Iceland' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IR', name: 'Iran, Islamic Republic Of' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IM', name: 'Isle of Man' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italy' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'JP', name: 'Japan' },
  { code: 'JE', name: 'Jersey' },
  { code: 'JO', name: 'Jordan' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'KP', name: 'Korea, Democratic People\'S Republic Of' },
  { code: 'KR', name: 'Korea, Republic Of' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'LA', name: 'Lao People\'S Democratic Republic' },
  { code: 'LV', name: 'Latvia' },
  { code: 'LB', name: 'Lebanon' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LY', name: 'Libyan Arab Jamahiriya' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MO', name: 'Macao' },
  { code: 'MK', name: 'Macedonia, The Former Yugoslav Republic Of' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MW', name: 'Malawi' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'MV', name: 'Maldives' },
  { code: 'ML', name: 'Mali' },
  { code: 'MT', name: 'Malta' },
  { code: 'MH', name: 'Marshall Islands' },
  { code: 'MQ', name: 'Martinique' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'YT', name: 'Mayotte' },
  { code: 'MX', name: 'Mexico' },
  { code: 'FM', name: 'Micronesia, Federated States Of' },
  { code: 'MD', name: 'Moldova, Republic Of' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MS', name: 'Montserrat' },
  { code: 'MA', name: 'Morocco' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'AN', name: 'Netherlands Antilles' },
  { code: 'NC', name: 'New Caledonia' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'NU', name: 'Niue' },
  { code: 'NF', name: 'Norfolk Island' },
  { code: 'MP', name: 'Northern Mariana Islands' },
  { code: 'NO', name: 'Norway' },
  { code: 'OM', name: 'Oman' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PW', name: 'Palau' },
  { code: 'PS', name: 'Palestinian Territory, Occupied' },
  { code: 'PA', name: 'Panama' },
  { code: 'PG', name: 'Papua New Guinea' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PN', name: 'Pitcairn' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RE', name: 'Reunion' },
  { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russian Federation' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'SH', name: 'Saint Helena' },
  { code: 'KN', name: 'Saint Kitts and Nevis' },
  { code: 'LC', name: 'Saint Lucia' },
  { code: 'PM', name: 'Saint Pierre and Miquelon' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines' },
  { code: 'WS', name: 'Samoa' },
  { code: 'SM', name: 'San Marino' },
  { code: 'ST', name: 'Sao Tome and Principe' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'SN', name: 'Senegal' },
  { code: 'RS', name: 'Serbia' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'SG', name: 'Singapore' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'SB', name: 'Solomon Islands' },
  { code: 'SO', name: 'Somalia' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands' },
  { code: 'ES', name: 'Spain' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'SD', name: 'Sudan' },
  { code: 'SR', name: 'Suriname' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen' },
  { code: 'SZ', name: 'Swaziland' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'SY', name: 'Syrian Arab Republic' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TJ', name: 'Tajikistan' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TL', name: 'Timor-Leste' },
  { code: 'TG', name: 'Togo' },
  { code: 'TK', name: 'Tokelau' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TT', name: 'Trinidad and Tobago' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'TR', name: 'Turkey' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'TC', name: 'Turks and Caicos Islands' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'UK', name: 'United Kingdom' },
  { code: 'US', name: 'United States' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Viet Nam' },
  { code: 'VG', name: 'Virgin Islands, British' },
  { code: 'VI', name: 'Virgin Islands, U.S.' },
  { code: 'WF', name: 'Wallis and Futuna' },
  { code: 'EH', name: 'Western Sahara' },
  { code: 'YE', name: 'Yemen' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe' }
];

export const MOCK_VIDEOS: VideoData[] = [
  {
    id: '1',
    title: 'Building a Clone of NewPipe in 10 Minutes',
    uploader: 'Tech Master',
    views: '1.2M views',
    date: '2 days ago',
    duration: '10:05',
    thumbnail: 'https://picsum.photos/seed/tech/640/360',
    platform: 'YouTube',
    avatar: 'https://picsum.photos/seed/avatar1/50/50',
    country: 'US'
  },
  {
    id: 'cricket1',
    title: 'LIVE: IND vs AUS - T20 World Cup Final 2024',
    uploader: 'ICC Official',
    views: '5.4M watching',
    date: 'Live Now',
    duration: 'Live',
    thumbnail: 'https://picsum.photos/seed/cricket/640/360',
    platform: 'YouTube',
    avatar: 'https://picsum.photos/seed/icc/50/50',
    country: 'IN'
  },
  {
    id: 'cricket2',
    title: 'IPL Live: CSK vs MI - Full HD Stream',
    uploader: 'Sports Central',
    views: '1.2M watching',
    date: 'Live Now',
    duration: 'Live',
    thumbnail: 'https://picsum.photos/seed/ipl/640/360',
    platform: 'Dailymotion',
    avatar: 'https://picsum.photos/seed/bcci/50/50',
    country: 'IN'
  },
  {
    id: '2',
    title: 'Funny Cat Compilation 2024 - Try Not To Laugh',
    uploader: 'MeowTube',
    views: '540K views',
    date: '5 hours ago',
    duration: '03:42',
    thumbnail: 'https://picsum.photos/seed/cats/640/360',
    platform: 'Dailymotion',
    avatar: 'https://picsum.photos/seed/avatar2/50/50',
    country: 'UK'
  },
  {
    id: '3',
    title: 'Crypto Market Crash? Bitcoin Analysis Live',
    uploader: 'BlockChain Daily',
    views: '89K views',
    date: 'Live',
    duration: 'Live',
    thumbnail: 'https://picsum.photos/seed/crypto/640/360',
    platform: 'Rumble',
    avatar: 'https://picsum.photos/seed/avatar3/50/50',
    country: 'US'
  },
  {
    id: '4',
    title: 'Amazing Dance Challenge #Viral',
    uploader: 'DanceTok',
    views: '2.5M views',
    date: '1 day ago',
    duration: '00:59',
    thumbnail: 'https://picsum.photos/seed/dance/360/640', 
    platform: 'TikTok',
    avatar: 'https://picsum.photos/seed/avatar4/50/50',
    country: 'BR'
  },
  {
    id: '5',
    title: 'Bangla Natok 2024 - New Release',
    uploader: 'CD Choice',
    views: '500K views',
    date: '1 day ago',
    duration: '45:20',
    thumbnail: 'https://picsum.photos/seed/natok/640/360',
    platform: 'YouTube',
    avatar: 'https://picsum.photos/seed/avatar5/50/50',
    country: 'BD'
  },
  {
    id: '6',
    title: 'Bollywood Hits 2024 Jukebox',
    uploader: 'T-Series',
    views: '30M views',
    date: '1 week ago',
    duration: '15:20',
    thumbnail: 'https://picsum.photos/seed/hindi/640/360',
    platform: 'YouTube',
    avatar: 'https://picsum.photos/seed/avatar6/50/50',
    country: 'IN'
  },
  {
    id: '7',
    title: 'Anime Opening Collection',
    uploader: 'Crunchyroll',
    views: '2M views',
    date: '3 days ago',
    duration: '04:20',
    thumbnail: 'https://picsum.photos/seed/anime/640/360',
    platform: 'BiliBili',
    avatar: 'https://picsum.photos/seed/avatar7/50/50',
    country: 'JP'
  }
];

export const MOCK_TIKTOK_VIDEOS: VideoData[] = [
    {
      id: 'tt1',
      title: 'POV: You forgot to defrost the chicken 🐔',
      uploader: 'MamaCools',
      views: '5.2M views',
      date: '1 hour ago',
      duration: '00:45',
      thumbnail: 'https://picsum.photos/seed/tiktok1/360/640',
      platform: 'TikTok',
      avatar: 'https://picsum.photos/seed/avtt1/50/50',
      isShort: true,
      streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4'
    },
    {
      id: 'tt2',
      title: 'Satisfying Kinetic Sand ASMR',
      uploader: 'SandMaster',
      views: '10M views',
      date: '2 hours ago',
      duration: '01:00',
      thumbnail: 'https://picsum.photos/seed/sand/360/640',
      platform: 'TikTok',
      avatar: 'https://picsum.photos/seed/avtt2/50/50',
      isShort: true,
      streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
    },
    {
        id: 'tt3',
        title: 'New Dance Trend 2024 #MoveIt',
        uploader: 'DancerX',
        views: '1M views',
        date: '5 mins ago',
        duration: '00:30',
        thumbnail: 'https://picsum.photos/seed/dance2/360/640',
        platform: 'TikTok',
        avatar: 'https://picsum.photos/seed/avtt3/50/50',
        isShort: true,
        streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'
    }
];

export const MOCK_RUMBLE_VIDEOS: VideoData[] = [
    {
        id: 'rum1',
        title: 'Breaking: Major Tech Announcement Live',
        uploader: 'TechInsider',
        views: '250K views',
        date: 'Streamed 2h ago',
        duration: '1:45:00',
        thumbnail: 'https://picsum.photos/seed/news/640/360',
        platform: 'Rumble',
        avatar: 'https://picsum.photos/seed/avrum1/50/50',
        streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'
    },
    {
        id: 'rum2',
        title: 'Cute Dog Rescues Kitten',
        uploader: 'ViralAnimals',
        views: '50K views',
        date: '1 day ago',
        duration: '03:20',
        thumbnail: 'https://picsum.photos/seed/dogs/640/360',
        platform: 'Rumble',
        avatar: 'https://picsum.photos/seed/avrum2/50/50',
        streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'
    }
];

export const MOCK_PEERTUBE_VIDEOS: VideoData[] = [
    {
        id: 'pt1',
        title: 'Why Decentralization Matters',
        uploader: 'PrivacyGuy',
        views: '10K views',
        date: '1 week ago',
        duration: '12:00',
        thumbnail: 'https://picsum.photos/seed/code/640/360',
        platform: 'PeerTube',
        avatar: 'https://picsum.photos/seed/avpt1/50/50',
        streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
    },
    {
        id: 'pt2',
        title: 'Blender 4.0 Tutorial: Geometry Nodes',
        uploader: 'OpenSourceArt',
        views: '5K views',
        date: '3 days ago',
        duration: '25:30',
        thumbnail: 'https://picsum.photos/seed/3d/640/360',
        platform: 'PeerTube',
        avatar: 'https://picsum.photos/seed/avpt2/50/50',
        streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
    }
];


export const MOCK_TRENDING: VideoData[] = [
    ...MOCK_VIDEOS.slice(2, 6),
    ...MOCK_VIDEOS.slice(0, 2)
];

export const SAMPLE_VIDEO_URL = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4";
